sudo: required
language: generic

services:
  - docker

before_install: 
  - docker build -t kiminoto1412/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true kiminoto1412/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1" # Set your region to Asia Pacific (Singapore)
  app: "frontend" # Set your application name
  env: "frontend-env" # Set your environment name in lowercase
  bucket_name: "elasticbeanstalk-ap-southeast-1-891377290833" # Set your S3 bucket name
  bucket_path: "frontend" # set as app name
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"