sudo: required
services:
  - docker

before_install: 
  - docker build -t kiminoto1412/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true kiminoto1412/docker-react npm run test -- --coverage